In [6]:
import numpy as np
mat = np.ones([4,4])

In [7]:
print(mat)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
tst = mat[0:2, 0:2]


In [12]:
print(tst)

[[1. 1.]
 [1. 1.]]


In [13]:
tst[0,0] = 5
print(tst)

[[5. 1.]
 [1. 1.]]


In [14]:
print(mat)

[[5. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
tst2 = np.array([2,2]

In [17]:
plane0_neighbours = [(5,3), (1,3), (2,0), (3,3)]  # Plane 0 connect to side 3 of plane5, side 3 of plane1 etc.
plane1_neighbours = [(5,2), (4,1), (2,1), (0,1)]
plane2_neighbours = [(0,2), (1,2), (4,0), (3,0)]
plane3_neighbours = [(2,3), (4,3), (5,0), (0,3)]
plane4_neighbours = [(2,2), (1,1), (5,1), (3,1)]
plane5_neighbours = [(3,2), (4,2), (1,0), (0,0)]
neighbours = [plane0_neighbours, plane1_neighbours, plane2_neighbours, plane3_neighbours, plane4_neighbours, plane5_neighbours]

In [19]:
neighbours[0][2][1]


0

In [22]:
UV = [[0,1],[0,4],[1,5],[0,1]]
print(UV.count([0,11]))

0
