In [6]:


s1 = "a = b + c"
try:
    exec(s1)
except NameError:
    print("not yet possible")

b,c = 1,4
try:
    exec(s1)
except NameError:
    print("not yet possible")
print(a)
        

not yet possible
5


In [11]:
import re
s = "2R45L045R"
re.split(r"(\d+)", s)
#re.findall(r'(\d+|\w+)', s)

['', '2', 'R', '45', 'L', '045', 'R']

In [1]:
import numpy as np
map = np.ones((4,4))


In [2]:
print(map)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
print(map[0, :].all(1))

AxisError: axis 1 is out of bounds for array of dimension 1

In [8]:
print(map==2)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [9]:
map[0,0] = 2
print(map==2)

[[ True False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


print(np.pad(map, 1, 'constant', 4))


In [16]:
map = np.pad(map, 1, 'constant', constant_values=4)
print(map)

[[4. 4. 4. 4. 4. 4.]
 [4. 2. 1. 1. 1. 4.]
 [4. 1. 1. 1. 1. 4.]
 [4. 1. 1. 1. 1. 4.]
 [4. 1. 1. 1. 1. 4.]
 [4. 4. 4. 4. 4. 4.]]


In [17]:
map.print()


AttributeError: 'numpy.ndarray' object has no attribute 'print'