In [1]:
16%5


1

In [2]:
-16%5

4

In [6]:
li = [10, 20, 30, 40]
li.pop(2)
print(li)

[10, 20, 40]


li[2,4]

In [11]:
import numpy as np


In [12]:
a = np.arange(10)

In [13]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a = np.insert(a, 4, 1000)
print(a)

[   0    1    2    3 1000    4    5    6    7    8    9]


In [17]:
a = np.delete(a, 4)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = 10*a


In [20]:
print(b)


[ 0 10 20 30 40 50 60 70 80 90]


In [22]:
c = np.c_[a,b]

In [1]:
print(a)

NameError: name 'a' is not defined

In [4]:
import numpy as np
a = np.arange(10)
b = 10*a
c = np.c_[a,b]

In [11]:
print(c)

[[ 0  0]
 [ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]
 [ 6 60]
 [ 7 70]
 [ 8 80]
 [ 9 90]]


In [7]:
print(c[:,1])

[ 0 10 20 30 40 50 60 70 80 90]


In [10]:
np.where(c[:,0] == 7)[0][0]

7

In [12]:
c[7][0] = 5
c[5][0] = 7
np.where(c[:,0] == 7)[0][0]

5

In [13]:
print(c)

[[ 0  0]
 [ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 7 50]
 [ 6 60]
 [ 5 70]
 [ 8 80]
 [ 9 90]]


In [14]:
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(c)

[[ 0  0]
 [ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 7 50]
 [ 6 60]
 [ 5 70]
 [ 8 80]
 [ 9 90]]


In [17]:
c

array([[ 0,  0],
       [ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 7, 50],
       [ 6, 60],
       [ 5, 70],
       [ 8, 80],
       [ 9, 90]])

In [18]:
np.delete(c, 0, 0)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 7, 50],
       [ 6, 60],
       [ 5, 70],
       [ 8, 80],
       [ 9, 90]])

In [1]:
-1+6

5

In [2]:
-1%6

5

In [7]:
import numpy as np
a = np.array([[1],[2],[3]])

In [11]:
np.vstack((a, a))


array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [12]:
b = np.array([])

In [13]:
np.vstack((b, a))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 1