In [1]:
16%5


1

In [2]:
-16%5

4

In [6]:
li = [10, 20, 30, 40]
li.pop(2)
print(li)

[10, 20, 40]


li[2,4]

In [11]:
import numpy as np


In [12]:
a = np.arange(10)

In [13]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a = np.insert(a, 4, 1000)
print(a)

[   0    1    2    3 1000    4    5    6    7    8    9]


In [17]:
a = np.delete(a, 4)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = 10*a


In [20]:
print(b)


[ 0 10 20 30 40 50 60 70 80 90]


In [22]:
c = np.c_[a,b]

In [1]:
print(a)

NameError: name 'a' is not defined

In [4]:
import numpy as np
a = np.arange(10)
b = 10*a
c = np.c_[a,b]

In [5]:
print(a, b, c)

[0 1 2 3 4 5 6 7 8 9] [ 0 10 20 30 40 50 60 70 80 90] [[ 0  0]
 [ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]
 [ 6 60]
 [ 7 70]
 [ 8 80]
 [ 9 90]]


In [7]:
print(c[:,1])

[ 0 10 20 30 40 50 60 70 80 90]
